---
- name: Install and configure Red Hat Insights-client
  hosts: all
  collections:
    - redhatinsights.insights    
  become: true

  
tasks:
- name: install/update insights client 
  ansible.builtin.yum:
    name: insights-client
    state: latest
    
- include_role: 
  name: insights_client
    when: ansible_os_family == 'RedHat'
