---
- name: Patch Windows Servers
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
