---
collections:
- ansible.windows
- community.vmware
- vmware.vmware:2.5
- cloud.vmware_ops:1.9.0
- community.postgresql

# Note: this requirements.yml file is used to specify what Ansible collections are
# needed to launch playbooks in this project.
#pyVmomi>=6.7
#git+https://github.com/vmware/vsphere-automation-sdk-python.git ; python_version >= '2.7'  # Python 2.6 is not supported
