---
collections:
  - name: community.vmware
  - name: ansible.posix
  - name: community.general
  - name: ansible.windows

  # Optional but useful in your environment
  - name: redhat.rhel_system_roles
  - name: freeipa.ansible_freeipa
