---
collections:
  - name: ansible.windows
    # version: 

  - name: vmware.vmware
    # version: "2.5.0"

  - name: cloud.vmware_ops
    # version: "1.9.0"

  #- name: community.postgresql
  #- name: community.vmware
