---
collections:
  - name: community.vmware
  - name: ansible.posix
  - name: community.general
  - name: ansible.windows
#  - name: redhat.rhel_system_roles
#    source: https://console.redhat.com/api/automation-hub/
  - name: freeipa.ansible_freeipa
