---
- name: Patch Red Hat Enterprise Linux systems
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        security: true

    - name: Reboot system to apply updates
      ansible.builtin.reboot:

    - name: Wait for the system to come back online
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 320

    - name: Check if updates were applied
      ansible.builtin.shell: yum list updates
      register: result

    - name: Print result
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"
