---
- name: Install and configure Red Hat Satellite Server
  hosts: all
  become: true
  vars:
    rhsm_username: "mhillis@redhat.com" 
    rhsm_password: "DTXO\03ODY"
  collections:
  - ansible.posix
  - ansible.builtin
  - community.general

# to do:
# - break into roles 
# - Configure session recording (role).
# - Install common packages (role).
# - set tuned profile (role).
# - IDM enrollement (role).
# - attach new virt disk to vm. 
# - configure lvm disk for /var
# - Set SELinux context types and relabel
# - Remediation for CIS server lvl1 (role).

  tasks:

  - name: Register system to Red Hat subscription management nework.
    community.general.redhat_subscription:
      state: present
      username: '{{ rhsm_username }}'
      password: '{{ rhsm_password }}' 

  - name: Enable all required software repositories for Red Hat Satellite Server
    community.general.rhsm_repository:
      name: '{{ item }}'
      state: enabled
    loop:
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "satellite-6.14-for-rhel-8-x86_64-rpms"
      - "satellite-maintenance-6.14-for-rhel-8-x86_64-rpms"

  - name: Enable and start 'firewalld' service
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true

  - name: Configure Firewalld for Red Hat Satellite Server
    ansible.posix.firewalld:
      zone: public
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - "80/tcp"
      - "443/tcp"
      - "5647/tcp"
      - "8000/tcp"
      - "8140/tcp"
      - "9090/tcp"
      - "5000/tcp"
      - "53/udp"
      - "67/udp"
      - "69/udp"

  - name: Reload 'firewalld' service
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: Update all system packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Enable required dnf module for Red Hat Satellite Server
    ansible.builtin.dnf:
      name: '@satellite:el8'
      state: present  
      
  - name: Install required rpms for Red Hat Satellite Server
    ansible.builtin.dnf:
      name: "satellite"
      state: latest

# satellite-installer --scenario satellite \
# --foreman-initial-organization "openincite.net" \
# --foreman-initial-location "Amesbury" \ 
# --foreman-initial-admin-username admin \
# --foreman-initial-admin-password password \
# --enable-foreman-cli-ansible \
# --enable-foreman-cli \
# --enable-foreman-cli-katello \
