---
- name: Install and configure Red Hat Satellite Server
  hosts: all
  become: true
  vars:
    rhsm_username: "username" 
    rhsm_password: "changeme"
    sat_verion: "6.14"
  collections:
  - ansible.posix
  - ansible.builtin
  - community.general

# to do:
# - break into roles 
# - Configure session recording (role).
# - Install common packages (role).
# - set tuned profile (role).
# - IDM enrollement (role).
# - attach new virt disk to vm. 
# - configure lvm disk for /var
# - Set SELinux context types and relabel
# - Remediation for CIS server lvl1 (role).

  tasks:

  - name: Register system to Red Hat subscription management nework.
    community.general.redhat_subscription:
      state: present
      username: '{{ rhsm_username }}'
      password: '{{ rhsm_password }}' 

  - name: Enable all required software repositories for Red Hat Satellite Server
    community.general.rhsm_repository:
      name: '{{ item }}'
      state: enabled
    loop:
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "satellite-6.14-for-rhel-8-x86_64-rpms"
      - "satellite-maintenance-6.14-for-rhel-8-x86_64-rpms"

  - name: Enable and start 'firewalld' service
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true

  - name: Configure Firewalld for Red Hat Satellite Server
    ansible.posix.firewalld:
      zone: public
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - "80/tcp"
      - "443/tcp"
      - "5647/tcp"
      - "8000/tcp"
      - "8140/tcp"
      - "9090/tcp"
      - "5000/tcp"
      - "53/udp"
      - "67/udp"
      - "69/udp"

  - name: Reload 'firewalld' service
    ansible.builtin.service:
      name: firewalld
      state: reloaded

  - name: Update all system packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

#  - name: Enable required dnf module for Red Hat Satellite Server
#    ansible.builtin.dnf:
#      name: '@satellite:el8'
#      state: present  

  - name: Enable ruby:2.7 and postgresql:12 modules for RHEL 8
    ansible.builtin.dnf:
      name: '{{ item }}'
      state: present
    with_items:
      - '@ruby:2.7'
      - '@postgresql:12'
    when: ansible_distribution_major_version == '8' and sat_version >= 6.14
  
# Workaround for @satellite:el8 until https://github.com/ansible/ansible/pull/76277 is resolved
- name: Enable satellite:el8 module for RHEL 8
  ansible.builtin.copy:
    dest: '/etc/dnf/modules.d/{{ item }}'
    src: 'files/{{ item }}'
  with_items:
    - pki-core.module
    - pki-deps.module
    - satellite.module
  - name: Install required rpms for Red Hat Satellite Server
    ansible.builtin.dnf:
      name: "satellite"
      state: latest
  - name: Enable satellite:el8 module for RHEL 8
    ansible.builtin.copy:
      dest: '/etc/dnf/modules.d/{{ item }}'
      src: 'files/{{ item }}'
    with_items:
      - pki-core.module
      - pki-deps.module
      - satellite.module
    when: ansible_distribution_major_version == '8' and sat_version >= 6.16

# satellite-installer --scenario satellite \
# --foreman-initial-organization "openincite.net" \
# --foreman-initial-location "Amesbury" \ 
# --foreman-initial-admin-username admin \
# --foreman-initial-admin-password password \
# --enable-foreman-cli-ansible \
# --enable-foreman-cli \
# --enable-foreman-cli-katello \
