---
- name: Install and configure Red Hat Satellite Server
  hosts: all
  become: true
  vars:
    rhsm_username: changeme
    rhsm_password: password

  tasks:
  
# to do:
# - break into roles 
# - Configure session recording (role).
# - Install common packages (role).
# - set tuned profile (role).
# - IDM enrollement (role).
# - attach new virt disk to vm. 
# - configure lvm disk for /var
# - Set SELinux context types and relabel
# - Remediation for CIS server lvl1 (role).

  - name: Register system to subscription management nework.
    community.general.redhat_subscription:
      state: present
      username: '{{ rhsm_username }}'
      password: '{{ rhsm_password }}' 

  - name: Enable required software repositories
    community.general.redhat_subscription:
      name: '{{ item }}'
      state: enabled
    loop:
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "satellite-6.14-for-rhel-8-x86_64-rpms"
      - "satellite-maintenance-6.14-for-rhel-8-x86_64-rpms"

  - name: Enable required dnf module for satellite
    ansible.builtin.dnf:
      name: '@satellite:el8'
      state: present   

  - name: Update all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    
  - name: Install required rpms
    ansible.builtin.dnf:
      name: "satellite"
      state: latest
    
  - name: Enable and start firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: true

  - name: Configure Firewall
    ansible.builtin.firewalld:
      zone: public
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
      - "80/tcp"
      - "443/tcp"
      - "5647/tcp"
      - "8000/tcp"
      - "8140/tcp"
      - "9090/tcp"
      - "5000/tcp"
      - "53/udp"
      - "67/udp"
      - "69/udp"

  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
