---
- name: Provision RHEL9 VM on VMware ESXi
  hosts: localhost
  gather_facts: no
  # Requires vmware.vmware collection to be installed in the Execution Environment

  vars:
    # --- CONNECTION VARIABLES (MUST BE UPDATED) ---
    vcenter_hostname: "your-esxi-or-vcenter-host"  # e.g., vcenter.yourdomain.local or 192.168.1.10
    vcenter_admin: "root"
    vcenter_username: "{{ vcenter_admin }}@{{ vcenter_hostname }}"
    vcenter_password: "your_password"              # SECURE THIS IN AN ANSIBLE VAULT!
    datacenter_name: "Datacenter"                  # The name of your vSphere Datacenter
    cluster_name: "{{ vcenter_hostname }}"         # Use Cluster name or ESXi hostname for standalone ESXi
    datastore_name: "datastore1"                   # Name of the datastore for the VM disk
    
    # --- VM SPECIFICATION VARIABLES ---
    vm_name: "RHEL9-VM"
    vm_folder: "/"                                 # Root VM folder, use '/DataCenterName/vm' if using vCenter
    vm_guest_id: "rhel9_64Guest"                   # Guest OS ID for RHEL 9 (required)
    vm_memory_mb: 8192                             # 8GB RAM
    vm_num_cpus: 4
    vm_disk_size_gb: 60
    # The 'vmware.vmware.vm' module uses a list of controllers, but we can simplify here
    vm_scsi_type: "pvscsi"                         

    # --- NETWORK & INSTALL MEDIA ---
    network_name: "VM Network"                     # Name of the port group/network interface
    iso_datastore_path: "[nas00] iso/rhel9_network_install.iso" # Full datastore path to your ISO

  tasks:
    - name: Create RHEL9 virtual machine and configure hardware
      vmware.vmware.vm:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        cluster: "{{ cluster_name }}"
        resource_pool: "{{ cluster_name }}"
        state: present 
        guest_id: "{{ vm_guest_id }}"
        
        # --- NEW HARDWARE CONFIGURATION STRUCTURE ---
        # 1. CPU and Memory are now top-level parameters
        cpu: "{{ vm_num_cpus }}"
        memory: "{{ vm_memory_mb }}" # Note: module expects MB, which matches your variable
        
        # 2. SCSI Controller is now defined via scsi_controllers (list of dicts)
        scsi_controllers:
          - type: "{{ vm_scsi_type }}" # e.g., pvscsi

        # 3. Disks is now PLURAL (disks)
        disks:
          - size_gb: "{{ vm_disk_size_gb }}"
            type: thin
            datastore: "{{ datastore_name }}"
            # Link disk to the PVSCSI controller created above (default key '0')
            controller_key: 1000 

        # 4. CDROM is now PLURAL (cdroms)
        cdroms:
          - type: iso
            iso_path: "{{ iso_datastore_path }}"
            # Link CDROM to the default IDE controller (key 200)
            controller_key: 200 

        # 5. Networks is now PLURAL (network_adapters)
        network_adapters:
          - name: "{{ network_name }}"
            type: vmxnet3
            state: present # Must be present if creating
            
        # 6. Removing unsupported wait_for_ip_address: no
        # --- END NEW HARDWARE CONFIGURATION STRUCTURE ---

    - name: Power on the VM to start RHEL installation
      vmware.vmware.vm_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
        datacenter: "{{ datacenter_name }}"
        state: powered-on
