---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: false
  collections:
   - community.vmware

  tasks:
   - name: Clone the template
     community.vmware.vmware_guest:
      validate_certs: false
      folder: /vmfs/volumes/
      name: "{{ wmware_vmname }}"
      state: poweredon
      template: "lesath.openincite.net"
      hardware:
       memory_mb: "{{ vmware_mem }}"
       num_cpus: "{{ vmware_cpu }}"
      disk:
       - size_gb: "{{ vmware_disk }}"
         type: "thin"
         datastore: datastore1
      networks:
       wait_for_ip_address: false
